name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install jq
      run: sudo apt-get install jq
    - name: Where's jq?
      run: which jq
    - name: Display environment
      run: echo $(env | sort)
    - name: Update configs
      run: ./update_config.sh
