name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Display environment
      run: echo $(env | sort)
    - name: Update configs
      env:
        UAT_ENV: ${{ secrets.UAT_ENV }}
      run: ./update_config.sh
